name: MLflow CI Pipeline (Advance)

on:
  push:
    branches: ["main"]

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow scikit-learn pandas docker

    # ================= TRAIN =================
    - name: Train model with MLflow
      run: |
        cd MLProject
        python modelling.py

    # ================= GET RUN ID =================
    - name: Get MLflow Run ID
      run: |
        cd MLProject
        RUN_ID=$(ls -td mlruns/0/* | head -n 1 | xargs basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "RUN_ID=$RUN_ID"

    # ================= UPLOAD ARTIFACT =================
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    # ================= DOCKER =================
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image with MLflow
      run: |
        cd MLProject
        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-housing:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-housing:latest
