name: CI/CD - Housing

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow scikit-learn pandas

    # ===== TRAIN MODEL =====
    - name: Train model
      run: |
        cd MLProject
        python modelling.py

    # ===== GET RUN ID (AMAN) =====
    - name: Get MLflow Run ID (SAFE)
      run: |
        cd MLProject
        RUN_ID=$(grep run_id -R mlruns/*/*/meta.yaml | head -n 1 | cut -d':' -f2 | tr -d ' ')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Detected RUN_ID=$RUN_ID"



    # ===== UPLOAD ARTIFACT =====
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    # ===== DOCKER =====
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Debug MLflow structure
      run: |
        cd MLProject
        tree mlruns || ls -R mlruns

    - name: Build Docker image with MLflow
      run: |
        cd MLProject
        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/Housing:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/Housing:latest
